#!/bin/bash
# Unofficial strict mode for bash
# See http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

# Importing functions
. ./functions/config.sh
. ./functions/create.sh
. ./functions/revert.sh
. ./functions/manual.sh
. ./functions/team_repo.sh


cli(){
	case $1 in 
		create)
			create $@
			;;
		help)
			helpFunc
			;;
		revert)
			revert $@
			;;
		team_add)
			team_add
			;;
		*)
		helpFunc
 		;;
	esac
}


cli $@
